<?php /** @var $block \ISM\Blog\Block\PostList  */ ?>
<h1><?php echo __('Latest Blog Posts') ?></h1>
<ul class="blog-post-list">
    <?php $_posts = $block->getPosts() ?>
    <?php /**  @var $post \ISM\Blog\Model\Post */ ?>
    <?php foreach ($_posts as $post): ?>
    <li class="blog-post-list-item">
        <h3 class="blog-post-item-title">
            <a href="<?php echo $post->getUrlKey() ?>"><?php echo $post->getTitle() ?></a>
        </h3>
        <div class="blog-post-item-content">
            <?php if($post->getImageUrl()): ?>
                <img src="<?= $block->getPostImageUrl($post->getImageUrl())?>">
            <?php endif; ?>
            <?php echo $post->getDescription() ?>
        </div>
        <div class="blog-post-item-meta">
            <strong><?php echo __('Created at:')?></strong> <?php echo $post->getCreatedAt() ?>
        </div>
    </li>
    <?php endforeach; ?>
</ul>